/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/1sxBR22NfFY
 */
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Link } from 'react-router-dom';

export function Login() {
  return (
    <div className="flex items-center min-h-screen px-4">
      <div className="w-full max-w-sm space-y-4 mx-auto">
        <div className="space-y-2 text-center">
          <h1 className="text-3xl font-bold">Login</h1>
          <p className="text-gray-500 dark:text-gray-400">Enter your email below to login to your account</p>
        </div>
        <div className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="email">Email</Label>
            <Input id="email" placeholder="m@example.com" required type="email" />
          </div>
          <div className="space-y-2">
            <div className="flex items-center">
              <Label htmlFor="password">Password</Label>
              <a className="ml-auto inline-block text-sm underline" href="#">
                Forgot your password?
              </a>
            </div>
            <Input id="password" required type="password" />
          </div>
          <div className="space-y-2">
            <Link to="/dashboard">
              <Button className="w-full" type="submit">
                Login
              </Button>
            </Link>
          </div>
        </div>
        <div className="mt-4 text-center text-sm">
          Don't have an account?{' '}
          <a className="underline" href="#">
            Sign up
          </a>
        </div>
      </div>
    </div>
  );
}
